name: lint

on: 
  push:
    branches:
      - master
    pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.8'
      - name: cfn-lint
        run: |
          pip install cfn-lint==0.52.0
          cfn-lint -t '**/*.yaml'
          